/** Tên icon hợp lệ cho `RailIcon.vue`. */
export type RailIconName =
  | 'panelCollapse'
  | 'panelExpand'
  | 'monitor'
  | 'pipeline'
  | 'catalog'
  | 'rules'
  | 'agent'
  | 'skills'
  | 'quickAction'
  | 'knowledge'
  | 'runner'
  | 'automations'
  | 'logs'
  | 'statistics'
  | 'settings'
